### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException at de.undercouch.bson4jackson.io.DynamicOutputBuffer

### ISSUE THREAD

**Issue by tazija** [michel-kraemer/bson4jackson#27]
Hello, I'm encountering out of bounds runtime exception during BSON generation

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: -32768
    at java.util.ArrayList.get(ArrayList.java:324)
    at de.undercouch.bson4jackson.io.DynamicOutputBuffer.getBuffer(DynamicOutputBuffer.java:262)
    at de.undercouch.bson4jackson.io.DynamicOutputBuffer.putUTF8(DynamicOutputBuffer.java:550)
    at de.undercouch.bson4jackson.io.DynamicOutputBuffer.putUTF8(DynamicOutputBuffer.java:531)
    at de.undercouch.bson4jackson.BsonGenerator._writeFieldName(BsonGenerator.java:347)
    at de.undercouch.bson4jackson.BsonGenerator._writeArrayFieldNameIfNeeded(BsonGenerator.java:328)
    at de.undercouch.bson4jackson.BsonGenerator.writeNull(BsonGenerator.java:543)
    at com.nuodb.migrator.resultset.format.bson.BsonOutputFormat.writeValues(BsonOutputFormat.java:100)
    at com.nuodb.migrator.resultset.format.FormatOutputBase.writeRow(FormatOutputBase.java:136)
```

**Comment by jartu** [comment]
Same problem here. This problem makes it impossible to use this library for large structures/files.
