### ISSUE TITLE
bson4jackson should be able to handle a unnested value

### ISSUE THREAD

**Issue by brfrn169** [michel-kraemer/bson4jackson#53]
An error occurred in the following case:
```
ObjectMapper objectMapper = new ObjectMapper(new BsonFactory());
Integer i = 100;
byte[] bytes = objectMapper.writeValueAsBytes(i);
objectMapper.readValue(bytes, Object.class); // an error occurred!
```

The error is as follows:
```
Exception in thread "main" java.io.EOFException
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readUnsignedByte(LittleEndianInputStream.java:114)
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readByte(LittleEndianInputStream.java:107)
	at de.undercouch.bson4jackson.BsonParser.nextToken(BsonParser.java:261)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:490)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2807)
	at Main.main(Main.java:15)
```

**Comment by michel-kraemer** [comment]
@brfrn169 The document you're creating is not a valid BSON document (according to the spec [1]). Can you please elaborate on your use case? Thanks!

Michel

[1] http://bsonspec.org/

**Comment by brfrn169** [comment]
@michel-kraemer Thank you for your reply.

I want to serialize a JSON value in BSON.
JSON includes not only a nested value(object, array) but also a unnested value such as string(e.g., "aaa") and Integer(e.g., 100).
I read the spec and I understood that BSON and JSON is not completely compatible.

Thanks,
Toshihiro Suzuki
