### ISSUE TITLE
IllegalStateException found when fuzzing bson4jackson

### ISSUE THREAD

**Issue by centic9** [michel-kraemer/bson4jackson#99]
When using fuzzy-testing via `Jazzer` on bson4jackson, the code-snippet below triggers the following unexpected exception.

```
Exception in thread "main" java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
	at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:989)
	at java.base/java.nio.charset.CharsetDecoder.flush(CharsetDecoder.java:672)
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readUTF(LittleEndianInputStream.java:300)
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readUTF(LittleEndianInputStream.java:230)
	at de.undercouch.bson4jackson.BsonParser.readString(BsonParser.java:569)
	at de.undercouch.bson4jackson.BsonParser.nextToken(BsonParser.java:283)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:442)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4717)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3090)
	at Crash_1d0a239577ab1cacf236a55d1f0141820853b4f4.main(Crash_1d0a239577ab1cacf236a55d1f0141820853b4f4.java:13)
```

```
public class Crash_1d0a239577ab1cacf236a55d1f0141820853b4f4 {
    static final String base64Bytes = "AAAAAApidWZmZXIAEG5leHRHZXQAubABABBuZXh0QWRkALj5AgAQZmlsbAC4+QIAEm5leHREb3dubG9hZFBvc2l0aW9uAAAAAAAAAAAAA3N0cmVhbQAAAAAAAm5hbWUABAAAAEZNNAACdXJsACoAAABodHRwczovL29yZi1saXZlLm9ycy1zaG91dGNhc3QuYXQvZm00LXEyYQACaW1hZ2VVcmwAPAAAAGh0dHBzOi8vdXBsb2FkLndpa2ltZWRpYS5vcmcvd2lraXBlZGlhL2NvbW1vbnMvMi8yNC9GTTQuc3ZnAAJ0ZW1wb1N0cmF0ZWd5AAgAAABkZWZhdWx0AAF0ZW1wbwAAAAAAAADwPwJzdHJlYW1UeXBlAAUAAABsaXZlAAp1c2VyABJzdGFydFRpbWVsb2FkUG9zaXRpb24AAAAAAAAAAAADc3RyZWFtAAAAAAACbmFtZQAEAAAARk00AAJ1cmwAKgAAAGh0dHBzOi8vb3JmLWxpdmUub3JzLXNob3V0Y2FzdC5hdC9mbTQtcTJhAAJpbWFnZVVybAA8AAAAaHR0cHM6Ly91cGxvYWQud2lraW1lZGlhLm9yZy93aWtpcGVkaWEvaW8vZGF0YQAA";

    public static void main(String[] args) {
        byte[] input = java.util.Base64.getDecoder().decode(base64Bytes);
		try {
			new ObjectMapper(new BsonFactory()).readTree(input);
		} catch (IOException e) {
			// expected here
		}
    }
}
```

It seems some invalid input can confuse the internal decoding logic. Would be good to at least wrap this in one of the exceptions that are documented by Jackson, i.e. StreamReadException or IOException.

**Comment by michel-kraemer** [comment]
Nice catch. Thank you!
